cpdb/cpdb-frontend.c
cpdb/cpdb-frontend.h
cpdb/cpdb.h

glib headers should no longer be included inside `extern "C" { ... }` blocks.

fix for glib e38982df commit

---

cpdb/cpdb-frontend.c
cpdb/cpdb-frontend.h
cpdb/cpdb.h
cpdb/interface/org.openprinting.Backend.xml
cpdb/interface/org.openprinting.Frontend.xml
demo/print_frontend.c

- synchronously fetch printer list from backends, when calling `cpdbConnectToDbus()`
- backends will automatically signal any printer updates instead of having to manually ask them
- added printer-state-changed signal from backends]
- added javadoc comments to function declarations

synchronous printer fetching upon backend activation

---

cpdb/cpdb-frontend.c
cpdb/cpdb-frontend.h
cpdb/cpdb.h
cpdb/interface/org.openprinting.Backend.xml
demo/print_frontend.c

* Added cpdbGetAllTranslations() to synchronously fetch all printer string translations
* Added cpdbAcquireTranslations() to asychronously fetch them.
* Removed get-human-readable-option/choice-name methods Backend
* Removed cpdb_async_obj_t from cpdb-frontend.h as that is meant for internal use.

Add fetch all printer strings translations

---

cpdb.pc.in
cpdb/cpdb-frontend.c
cpdb/cpdb-frontend.h
cpdb/cpdb.h

The frontend should only shout in D-Bus to see which backends are there and to communicate with them. It cannot browse any directory in the host's or backend's file system.

Removes file system access

---

tools/cpdb-text-frontend.c

Quit the text frontend when scanf returns EOF,
which e.g. happens when the user presses Ctrl-D.
Previously, pressing Ctrl-D would result in the loop running indefinitely, printing ">" without end.

text-frontend: Quit on EOF

---

tools/cpdb-text-frontend.c

Instead of crashing due to a NULL dereference,
print a message and skip further processing of
the current command when `cpdbFindPrinterObj`
returns NULL, e.g. because the user has entered
the name of a nonexisting printer or backend.
For some commands, null checks were in place
without printing a message. Unify that.

text-frontend: Don't crash when printer doesn't exist

---

cpdb/cpdb-frontend.c
cpdb/cpdb-frontend.h

Use `const char*` instead of `char*` for the `backend` param of `cpdbRefreshPrinterList`. The function was recently added in
commit 17a1d82d7526c33591879bd97d961405212b408f
Author: Biswadeep Purkayastha <98874428+metabiswadeep@users.noreply.github.com>
Date:   Thu Jun 27 19:27:08 2024 +0530
API functions to refresh printer list and to get D-Bus connection (#35)
- Added API function cpdbRefreshPrinterList() to refresh the printer list
- Turned static function get_dbus_connection() into API function cpdbGetDbusConnection()
`const char*` is the usual way to pass C strings.
That also simplifies using the function, see
e.g. comment [1] in one of the changes of a pending change series implementing/updating CPDB support
for the LibreOffice print dialog.
[1] …

Pass backend name to cpdbRefreshPrinterList as const char*

---

cpdb/cpdb-frontend.c
cpdb/cpdb.c
cpdb/cpdb.h
tools/cpdb-text-frontend.c

GLib's `g_strdup` already provides the same functionality as `cpdbGetStringCopy`, so there's no need to have a custom implementation and even make that part of the public API.
Therefore, replace all uses of `cpdbGetStringCopy` with `g_strdup` and drop `cpdbGetStringCopy`.
[1] https://docs.gtk.org/glib/func.strdup.html

Replace cpdbGetStringCopy with g_strdup

---

cpdb/cpdb-frontend.c
cpdb/cpdb-frontend.h

Drop `cpdb_frontend_obj_s::own_id`,
since it's effectively unused since
commit 8f9e0544aa6bd244b79b310f76b2478d407006cc
Date:   Fri May 31 00:04:43 2024 +0530
Add new backends while the dialog is open, let frontend not be D-Bus service (#32)

frontend: Drop unused 'own_id' member

---

cpdb/cpdb.c

`cpdbConcatPath` allocates a new string, so
free it if it's not returned.
The value is not used in other code paths,
as `config_dir` is assigned something else.

Fix a memory leak in cpdbGetSysConfDir

---

cpdb/cpdb.c

Instead of using `CPDB_SYSCONFDIR` again as was
already done above, and doing so in a loop,
use the actual path extracted from the
`XDG_CONFIG_DIRS` environment variable.
That had already been the case earlier, before
it was changed to use `CPDB_SYSCONFDIR`
commit 20d62e35a1028800fc3b9926e4ac10184815d270
Date:   Sun Dec 18 00:35:07 2022 +0530
better debugging & code refactoring
, which at first glance looks like a copy-paste
mistake.

cpdbConcatPath: Actually check XDG_CONFIG_DIRS

---

cpdb/cpdb.c
cpdb/cpdb.h
tools/cpdb-text-frontend.c

This allows third-party applications to easily manage different CPDB releases.
This is especially important when shipping pre-built binaries of such applications implementing CPDB, as the end users may be running outdated and potentially vulnerable versions of CPDB.

Add capability to check CPDB version at runtime

---

tools/cpdb-text-frontend.c

Add a null check in handling of the "get-default-printer" command.
Instead of crashing, asking for the default printer for a non-existing backend now prints a message:
> get-default-printer-for-backend invalid
[Error] [Frontend] Error getting default printer for backend : GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.openprinting.Backend.invalid was not provided by any .service files
No default printer for backend found

text-frontend: Add null check for get-default-printer

---

tools/cpdb-text-frontend.c

Instead of only supporting the LANGUAGE environment variable that's not necessarily set, use GLib's `g_get_language_names` to detect the locale to use in the text frontend which takes other environment variables into account as well [1]:
> The returned list is sorted from most desirable to
> least desirable and always contains the default locale “C”.
Also, make `locale` a local variable in the control thread that's the only user instead of using a static variable.
This e.g. makes
> get-all-translations PDF CUPS
print the translations for the current language in a fresh Ubuntu 23.10 installation where the `LANGUAGE` environment variable is not set, and the result without this commit in place was therefore just
> get-all-translations PDF CUPS
No translations found
[1] …

text-frontend: Get locale via GLib

---

tools/cpdb-text-frontend.c

`dialog_bus_name` is unused since
commit c990f2ddbd000636e57cf4a8e976e1b2b04648bf
Date:   Mon Jul 10 14:21:22 2017 +0530
shift dbus code to FrontendObj
and `pid` is unused since
commit fb2686ba8f2fc60dc95ae0e2421e386922bf232e
Date:   Mon Jul 8 21:21:01 2024 +0530
Removed unused parameter instance_name (#41)
, so drop them, along with the then also unused `pid_temp`.

text-frontend: Drop unused local vars

---

tools/cpdb-text-frontend.c

The 2 strings allocated with `g_strdup` were never freed. There's no need to duplicate the strings in the first place, so just pass `option_name` and `option_val` as is.

text-frontend: Fix memory leak in "add-setting"

---

cpdb/cpdb-frontend.c
cpdb/cpdb.c
cpdb/cpdb.h

GLib's `g_strconcat` [1] already provides the functionality to concatenate strings, so there's no need to have `cpdbConcat` as a custom implementation and even make that part of the public API.
Therefore, replace the 2 uses of `cpdbConcat` with `g_strconcat` and drop `cpdbConcat`.
[1] https://docs.gtk.org/glib/func.strconcat.html

Replace cpdbConcat with g_strconcat

---

cpdb/cpdb.c
cpdb/cpdb.h

The way that `cpdbExtractFileName` casts a `const char*` to a `char*` and returns a `char*` looks suspicious, as the signature seems to suggest that it would be the caller's responsibility to free the returned string, but it is not actually the owner, as no new string was allocated.
In any case, `cpdbExtractFileName`, or more precisely its predecessor `extract_file_name` is unused
since
commit cde7d1dcf6fded0ec1147d87eaee5114e78b3c23
Date:   Thu Aug 24 20:57:57 2017 +0530
Remove the backend specific parts from original code
and the then already unused function was later renamed to `cpdbExtractFileName` in
commit b394eaa2369fe105bb4e28222456c0239110070f
Date:   Sun Aug 14 09:41:25 2022 +0200
Renamed all API functions, data types and constants
Since the function is neither used here in …

Drop unused cpdbExtractFileName

---

cpdb/cpdb-frontend.c

As described in [1], `g_variant_get` in
`print_backend_call_get_default_printer_sync` does the following:
> Upon encountering s, o or g, g_variant_get() takes a pointer to a (gchar*)
> (ie: (gchar **)) and sets it to a newly-allocated copy of the
> string. It is appropriate to free this copy using g_free().
Therefore, free the string copy using `g_free` in
`cpdbGetDefaultPrinterForBackend`.
This fixes this memroy leak reported by valgrind:
==58581== 4 bytes in 1 blocks are definitely lost in loss record 7 of 1,365
==58581==    at 0x4843808: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==58581==    by 0x4915B81: g_malloc (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8200.0)
==58581==    by 0x49324E2: g_strdup (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8200.0) …

Fix memory leak in cpdbGetDefaultPrinterForBackend

---

cpdb/cpdb-frontend.c
cpdb/cpdb-frontend.h

Before, even after using cpdbGetAllTranslations, trying to use cpdbGetOptionTranslation/cpdbGetChoiceTranslation would make dbus calls for those options and choices which did not have translations, which are not necessary and only cause further slowing down of the process of trying to simply use the translations table to get the corresponding translations.

Allow to extract translations from table

---

cpdb/cpdb-frontend.c

The string allocated with `g_strdup` was never freed.
There's no reason to duplicate the string, just use `service_name` directly.
This fixes a memory leak seen e.g. when running
cpdb-text-frontend and printing a file like this:
print-file /tmp/test.pdf PDF CUPS
Relevant valgrind output:
==550231== 30 bytes in 1 blocks are definitely lost in loss record 497 of 1,343
==550231==    at 0x4843808: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==550231==    by 0x4916B81: g_malloc (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8200.1)
==550231==    by 0x49334E2: g_strdup (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8200.1)
==550231==    by 0x485ACB5: g_strdup_inline (gstrfuncs.h:321)
==550231==    by 0x485ACB5: cpdbCreateBackend (cpdb-frontend.c:496)
==550231==    by …

Fix memory leak in cpdbCreateBackend

---

cpdb/cpdb-frontend.c

`printer_name` was never freed.
The newly allocated string is never used,
so just drop the variable altogether.
Fixes a memory leak with this valgrind output
seen with LibreOffice WIP CPDB change when printing [1]:
==546760== 42 bytes in 3 blocks are definitely lost in loss record 2,228 of 5,439
==546760==    at 0x4843808: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==546760==    by 0x130789EA: cpdbConcatSep (cpdb.c:84)
==546760==    by 0x130664D8: cpdbRefreshPrinterList (cpdb-frontend.c:330)
==546760==    by 0xDFAFAC5: psp::CPDManager::endSpool(rtl::OUString const&, rtl::OUString const&, _IO_FILE*, psp::JobData const&, bool, rtl::OUString const&) (cpdmgr.cxx:626)
==546760==    by 0xE0AD11E: PspSalPrinter::StartJob(rtl::OUString const*, rtl::OUString const&, …

Fix memory leak in cpdbRefreshPrinterList

---

cpdb/cpdb-frontend.c

Fix memory leak in cpdbPrintFileWithJobTitle

---

tools/cpdb-text-frontend.c

Add a local variable for the job ID returned as a
newly allocated string and free it.
Fixes this memory leak shown by valgrind:
==127622== 43 bytes in 2 blocks are definitely lost in loss record 754 of 1,370
==127622==    at 0x4843808: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==127622==    by 0x4916B81: g_malloc (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8200.1)
==127622==    by 0x49334E2: g_strdup (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8200.1)
==127622==    by 0x495BE61: ??? (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8200.1)
==127622==    by 0x495BAEF: ??? (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8200.1)
==127622==    by 0x495CC7D: g_variant_get_va (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8200.1)
==127622==    by 0x495CEF2: …

text-frontend: Fix memory leak in "print-file"

---

cpdb/cpdb-frontend.c

As the `g_variant_builder_new` doc [1] says:
> You should call `g_variant_builder_unref()` on the return value when
> it is no longer needed. The memory will not be automatically freed by
> any other call.
This fixes a memory leak in `cpdbSerializeToGVariant`.
Corresponding valgrind output without this commit in place when printing a file using cpdb-text-frontend:
==127622== 144 bytes in 1 blocks are definitely lost in loss record 1,262 of 1,370
==127622==    at 0x4843808: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==127622==    by 0x4916B81: g_malloc (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8200.1)
==127622==    by 0x495A376: g_variant_builder_new (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8200.1)
==127622==    by 0x485E909: cpdbSerializeToGVariant …

Unref GVariantBuilder to fix memory leak

---

cpdb/cpdb-frontend.c

The string needs to be freed, see the example in
the `g_variant_iter_next` doc [1].
Fixes a memory leak.
Corresponding valgrind output when printing a file using cpdb-text-frontend:
==164170== 4,751 bytes in 231 blocks are definitely lost in loss record 1,338 of 1,339
==164170==    at 0x4843808: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==164170==    by 0x4916B81: g_malloc (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8200.1)
==164170==    by 0x49334E2: g_strdup (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8200.1)
==164170==    by 0x495BE61: ??? (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8200.1)
==164170==    by 0x495D240: g_variant_iter_next (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8200.1)
==164170==    by 0x485AA3E: cpdbActivateBackends …

Fix memory leak in cpdbActivateBackends

---

cpdb/cpdb-frontend.c

If an error occurs when calling
`print_backend_call_do_listing_sync`, log the error, and free the memory.
When printing a file using cpdb-text-frontend using
> print-file /tmp/test.pdf PDF CUPS
and then exiting, this now logs the following error in my setup:
Error: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method doListing is not implemented on interface org.openprinting.PrintBackend
This also fixes this memory leak seen
previously, as reported by valgrind:
==167205== 149 (16 direct, 133 indirect) bytes in 1 blocks are definitely lost in loss record 1,254 of 1,342
==167205==    at 0x4843808: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==167205==    by 0x4916B81: g_malloc (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8200.1)
==167205==    by 0x4931C5C: …

Log and free GError in call to "doListing"

---

cpdb/cpdb-frontend.c

`service_name` already gets freed further up in the function and is never assigned a new value after this, so trying to free it again is problematic.
This fixes this GCC 14 `-Werror=use-after-free` warning in a `-Wall -Werror` build:
cpdb-frontend.c:1439:5: error: pointer 'service_name' may be used after 'free' [-Werror=use-after-free]
1439 |     free(service_name);
|     ^~~~~~~~~~~~~~~~~~
cpdb-frontend.c:1383:5: note: call to 'free' here
1383 |     free(service_name);
|     ^~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Fix potential double-free in cpdbResurrectPrinterFromFile

---

cpdb/cpdb-frontend.c

Return NULL in `background_thread`, as
the return type is `gpointer`.
Fixes this error in a `-Wall -Werror` build:
cpdb-frontend.c: In function 'background_thread':
cpdb-frontend.c:465:1: error: control reaches end of non-void function [-Werror=return-type]
465 | }
| ^

Return something in non-void function

---

cpdb/cpdb-frontend.c

Make sure the memory of the printer objects get
freed when the `cpdb_frontend_obj_s::printer`
`GHashTable` is destroyed, by passing a function
that calls `cpdbDeletePrinterObj` as the
function to free the memory allocated for each
value, as the values are `cpdb_printer_obj_t`
objects.
Therefore, just calling `g_free` isn't sufficient.
This fixes a memory leak as reported e.g.
by valgrind when just starting and stopping
cpdb-text-frontend with the CUPS backend
available.
Corresponding valgrind output reporting the
memory leak without this commit in place:
==231295== 624 (48 direct, 576 indirect) bytes in 3 blocks are definitely lost in loss record 1,307 of 1,323
==231295==    at 0x48489F3: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==231295==    by 0x4916BD9: …

Delete printer objects when deleting hash table

---

cpdb/cpdb-frontend.c

Free the memory allocated for more of the
`cpdb_printer_obj_t` string members.
While at it, also use `g_free` for the `backend_name` member, which removes the need to do a NULL check
manually, as `g_free` (other than plain `free`)
handles NULL just fine. [1]
This fixes a memory leak seen e.g. when running
cpdb-text-frontend (and the CUPS CPDB backend
available) even with the previous commit from
pull request [2] in place that causes `cpdbDeletePrinterObj` to be called for each printer object.
(Without [2], the memory leak is not fixed, as
`cpdbDeletePrinterObj` never gets called when
the hash table is destroyed in the first place.)
Corresponding valgrind output with [2] but not this commit in place:
==232997== 237 bytes in 18 blocks are definitely lost in loss record 1,217 of 1,273 …

Free printer object string members in cpdbDeletePrinterObj

---

cpdb/cpdb-frontend.c
cpdb/cpdb-frontend.h

Drop this, as it is unused since
commit 85447e866863ebc7327a32f16e86cba6f487bed3
Date:   Sat Mar 16 20:49:05 2024 +0530
Stream print data through a Unix domain socket (#30)
To ease making a Snap from the CPDB backend for CUPS (and
other CPDB backends in the future) we now transfer the print
job data from the dialog to the backend via a Unix domain socket
and not by dropping the data into a file.
In addition, we have done also the following changes:
- Removed support for the "FILE" CPDB backend.
- Removed API functions cpdbGetAllJobs(),
cpdbGetActiveJobsCount(), cpdbCancelJob(), and
cpdbPrintFilePath() and the corresponding D-Bus
methods.
- Removed the appropriate commands, "get-all-jobs",
"get-active-jobs-count", and "cancel-job" from the
"cpdb-text-frontend" utility.

Drop unused cpdb_job_t and cpdbUnpackJobArray

---

cpdb/cpdb-frontend.c

Free strings of the single option values
in the array before freeing the array itself.
Fixes a memory leak seen e.g. when running
cpdb-text-frontend and printing the options
of the CUPS-PDF printer using the
> get-all-options PDF CUPS
command. Corresponding valgrind output:
==286266== 1,761 bytes in 146 blocks are definitely lost in loss record 1,274 of 1,297
==286266==    at 0x4843808: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==286266==    by 0x4916B81: g_malloc (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8200.1)
==286266==    by 0x49334E2: g_strdup (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8200.1)
==286266==    by 0x485F600: g_strdup_inline (gstrfuncs.h:321)
==286266==    by 0x485F600: cpdbUnpackOptions (cpdb-frontend.c:2258)
==286266==    by …

Free option values in cpdbDeleteOption

---

cpdb/cpdb-frontend.c

Free the printer object created with
`cpdbGetNewPrinterObj` again.
Fixes a memory leak seen e.g. when using
the
> get-all-printers
command in cpdb-text-frontend.
Corresponding valgrind output:
==290968== 1,188 (312 direct, 876 indirect) bytes in 3 blocks are definitely lost in loss record 1,268 of 1,278
==290968==    at 0x48489F3: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==290968==    by 0x4916BD9: g_malloc0 (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8200.1)
==290968==    by 0x485BDF7: cpdbGetNewPrinterObj (cpdb-frontend.c:929)
==290968==    by 0x485B192: getAllPrintersLookup (cpdb-frontend.c:602)
==290968==    by 0x48FBCD2: g_hash_table_foreach (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8200.1)
==290968==    by 0x485B227: cpdbGetAllPrinters …

Fix memory leak in getAllPrintersLookup

---

cpdb/cpdb-frontend.c

`print_backend_call_get_option_translation_sync` calls `g_variant_get`, which already allocates a new string for `translation`, so there's no need to call `g_strdup` again.
Same for `cpdbGetChoiceTranslation` and `cpdbGetGroupTranslation`.
This fixes memory leaks seen e.g. with cpdb-text-frontend when using commands like these ones to print translation for options of the CUPS-PDF printer:
> get-option-translation output-bin PDF CUPS
Output Tray
> get-choice-translation output-bin face-down PDF CUPS
Face Down
Corresponding valgrind output:
==298753== 12 bytes in 1 blocks are definitely lost in loss record 55 of 1,289
==298753==    at 0x4843808: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==298753==    by 0x4916B81: g_malloc (in …

Fix memory leaks in cpdbGetOptionTranslation etc.

---

cpdb/cpdb-frontend.c

Try to open the file at the given file path before creating a print job using `cpdbPrintFD`.
Otherwise, passing an invalid path causes a print
job to be created that never gets processed.
For example, with cpdb-text-frontend, passing
an invalid path would print an error message:
> print-file /dummy/nonexistent PDF CUPS
[Error] [Frontend] Error opening file /dummy/nonexistent on PDF CUPS: No such file or directory
But it would still create a print job:
$ lpstat
PDF-209                 michi                0   2024-11-20T09:01:02 CET
That one would never get finished and has to be manually cancelled using `cancel <jobid>`.
(I noticed this because on KDE Plamsa, the printer widget was showing after that failed attempt, due to the pending print job.)
With this commit in place, the same error …

frontend: Check file before creating print job

---

CHANGES.md
cpdb/cpdb-frontend.c
cpdb/cpdb-frontend.h
tools/cpdb-text-frontend.c

@tillkamppeter 
This pull request enhances the cpdbGetNewFrontendObj() function to accept NULL for the callback parameter. When NULL is passed, the function will use the default cpdbPrinterCallback() function, which logs printer updates to the console. This makes the API simpler to use for applications that don't need custom printer update handling.
* Modified cpdbGetNewFrontendObj() in cpdb-frontend.c to use the default callback when NULL is passed
* Added a declaration for cpdbPrinterCallback() in cpdb-frontend.h to make it accessible to users
* Updated documentation in cpdb-frontend.h to reflect this change
* Updated the example in cpdb-text-frontend.c to demonstrate using NULL for the callback
* Updated CHANGES.md to document this enhancement
**Fixes #80 - Allow NULL for the callback …

Allow NULL for the callback in cpdbGetNewFrontendObj()

---

cpdb/cpdb-frontend.c

This pull request addresses issues related to double freeing and memory leaks in the CPDB library's printer object handling.
As suggested by @tillkamppeter in issue itself, I have made the following changes:
* Revised Memory Management: The responsibility for freeing printer objects has been moved from the callback function to the cpdbOnPrinterRemoved() function. This ensures that printer objects are freed immediately after the callback is executed.
* Updated Callback Logic: Removed the printer object freeing from the cpdbPrinterCallback() function to prevent **double-free errors** when custom callbacks are used.
These changes enhance the reliability of the CPDB API and simplify its usage, ensuring developers no longer need to worry about memory management issues.
**Fixes Issue #79 …

Fix Memory Management for Printer Objects in CPDB API
